parameters:
#    l3l0_labs_filesystem_archive.example.class: L3l0Labs\Bundle\FilesystemArchiveBundle\Example

services:
#    l3l0_labs_filesystem_archive.example:
#        class: %l3l0_labs_filesystem_archive.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
