Cocoders\Bundle\FilesystemArchiveBundle\Entity\Archive:
    type: entity
    table: archives
    id:
        id:
            type: integer
            generator: { strategy: IDENTITY }
    fields:
        name:
            column: name
            type: string
            length: 255
            unique: true
        archivedFiles:
            column: archived_files
            type: array
        uploadingFiles:
            column: uploading_files
            type: array
