parameters:
    l3l0_labs.archive.form_type.upload.class: Cocoders\Bundle\FilesystemArchiveBundle\Form\ArchiveUploadType

services:
    l3l0_labs.archive.form_type.upload:
        class: %l3l0_labs.archive.form_type.upload.class%

    l3l0_labs.archive.form.upload:
        class: Symfony\Component\Form\FormInterface
        factory_service: form.factory
        factory_method: createNamed
        arguments:
            - 'archive_upload'
            - @l3l0_labs.archive.form_type.upload
